package com.example.tsi.orestas.dulinskas.demoTest;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.junit.jupiter.api.Assertions.assertNull;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class CritiqueTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.edgedriver().setup();
    driver = new EdgeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void critique() {
    driver.get("http://54.234.206.230:3000/");
    driver.manage().window().maximize();
    driver.findElement(By.id("search-box")).click();
    driver.findElement(By.id("search-box")).sendKeys("x");
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.findElement(By.id("text-box")).click();
    driver.findElement(By.id("text-box")).sendKeys("test");
    driver.findElement(By.id("button")).click();
    driver.findElement(By.id("search-box")).click();
    driver.findElement(By.id("search-box")).sendKeys("x");
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.findElement(By.xpath("//input[@id=\'text-box\']")).click();
    driver.findElement(By.xpath("//input[@id=\'text-box\']")).sendKeys("1");
    driver.findElement(By.xpath("(//textarea[@id=\'text-box\'])[2]")).click();
    driver.findElement(By.xpath("(//textarea[@id=\'text-box\'])[2]")).sendKeys("update test");
    driver.findElement(By.xpath("(//button[@id=\'button\'])[2]")).click();
    driver.findElement(By.id("search-box")).click();
    driver.findElement(By.id("search-box")).sendKeys("x");
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.findElement(By.xpath("//input[@id=\'text-box\']")).click();
    driver.findElement(By.xpath("//input[@id=\'text-box\']")).sendKeys("1");
    driver.findElement(By.xpath("(//button[@id=\'button\'])[3]")).click();
    driver.close();
    String verifyAssertNull = null;
    assertNull(verifyAssertNull);
  }
}
