package com.example.tsi.orestas.dulinskas.demoTest;// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

import static org.junit.jupiter.api.Assertions.assertNull;

public class PenislandTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.edgedriver().setup();
    driver = new EdgeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void penislandTest() {
    driver.get("http://penisland.net/index.html");
    driver.manage().window().maximize();
    driver.findElement(By.linkText("Wood")).click();
    driver.findElement(By.linkText("Plastic")).click();
    driver.findElement(By.linkText("Samples")).click();
    driver.findElement(By.linkText("Testimonials")).click();
    driver.findElement(By.linkText("FAQ")).click();
    driver.findElement(By.linkText("Contact Us")).click();
    driver.close();
    String verifyAssertNull = null;
    assertNull(verifyAssertNull);
  }
}
